### ISSUE TITLE
While I am doing a curl request , getting 404 Error

### ISSUE THREAD

**Issue by kala725** [q-m/wp-json-api#1]
If I want to fetch json from a url to wordpress url using curl, I am getting 404 error, however it works fine in browser. How Can I get content using /api/get_post?post_id=123 . Is any header required ??

**Comment by rvw** [comment]
Hi @kala725, we forked the [official WP JSON API](https://wordpress.org/plugins/json-api/) plugin and made some small changes for our organization. In our setup, we can get the JSON either through the browser or with curl (without any extra headers).

I suggest you ask the same question in the [official support forum](https://wordpress.org/support/plugin/json-api), more people there.
